### ISSUE TITLE
Clarify Multiplicity of Element "patterns"

### ISSUE THREAD

**Issue by arcanefoam** [bluezio/ttc2016-live#2]
Looking at the Xtext language, for all Elements the set of keyword/value elements are inside a ( )\* [many] multiplicity... so this means that each element can do many actions?
E.g., AllIsntances could search for elements of two or more types, NewInstance can instantiate two or more elements (then the member value is a list?), the Get/SetAttribute can get/set two or more attributes?
For some it seems feasible, e.g. Set/Get attribute, for others seems not so clear.

**Comment by agarciadom** [comment]
No, this is only at the concrete syntax level - this is done so you can specify their fields in any order. In a previous version we didn't have this, and you'd have to always write things in a certain order (say, "field" then "type" then "target" for "AllInstances").

I suggest that you use the `dataflow.ecore` file in `eu.ttc.dataflow.model` instead to write your execution engine - the concrete syntax is meant to be convenient instead of an exact 1:1 mapping to the metamodel :-).
